image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim

options:
  size: 2x

definitions:
  services:
    docker:
      memory: 7168

pipelines:
  branches:
    master:
      - step:
          name: Deploy to Cloud Run
          deployment: production
          services:
            - docker
          caches:
            - docker
          script:
            - echo $GCLOUD_KEY | base64 -d > ${HOME}/gcloud-key.json
            - gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json
            - gcloud config set project rrhh-notificaciones
            - gcloud config set run/region southamerica-east1
            - docker build --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID --build-arg NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID --build-arg NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID --build-arg FIREBASE_SERVICE_ACCOUNT_KEY="$FIREBASE_SERVICE_ACCOUNT_KEY" -t southamerica-east1-docker.pkg.dev/rrhh-notificaciones/rrhh-notificaciones/rrhh-notificaciones-client .
            - gcloud auth configure-docker southamerica-east1-docker.pkg.dev
            - docker push southamerica-east1-docker.pkg.dev/rrhh-notificaciones/rrhh-notificaciones/rrhh-notificaciones-client
            - gcloud run deploy rrhh-notificaciones-client --image=southamerica-east1-docker.pkg.dev/rrhh-notificaciones/rrhh-notificaciones/rrhh-notificaciones-client --platform=managed --region=southamerica-east1 --allow-unauthenticated

      - step:
          name: Firebase Hosting Deploy
          image: node:20
          caches:
            - node
          script:
            - npm install -g firebase-tools
            - firebase deploy --only hosting --token "$FIREBASE_TOKEN"
